### ISSUE TITLE
Color suggestion

### ISSUE THREAD

**Issue by calderaricaio** [earlduque/Slack-Dark-Theme#11]
Hi guys, is that username label color a desirable thing to be adjusted?
I feel like the colors are not sooo good as they are right now, I can adjust it. Is that something you guys would like?

EX:
![screen shot 2018-10-05 at 17 10 12](https://user-images.githubusercontent.com/542722/46557853-b07c9c80-c8c1-11e8-96e6-72049bd0523b.png)

**Comment by earlduque** [comment]
Yeah, what's funny is that it's properly set for @mentions in threads but not in the general panel:
main window:
![image](https://user-images.githubusercontent.com/31702109/46770550-b51bc900-cca4-11e8-8ac9-8dceff4a6c47.png)
thread pane:
![image](https://user-images.githubusercontent.com/31702109/46770556-bc42d700-cca4-11e8-8891-b6dbbbfb03bd.png)

we should align them yeah. I'd probably vote that mentions should have the same dark background while mentions involving yourself are dark gray?

I'd say go for it, @calderaricaio !

**Comment by AnderYoo** [comment]
Hi, Could it be possible to make the font color more vivid/brightly?
The white font on the search tab is too blur to read except the highlighted keywords
![image](https://user-images.githubusercontent.com/33310155/49985096-15353100-ffae-11e8-9b8a-0c0caaf94ce4.png)

FYI, I'm using windows.
Thanks!
