### ISSUE TITLE
Find the CSS property that handles the "Loading history..." panel

### ISSUE THREAD

**Issue by earlduque** [earlduque/Slack-Dark-Theme#14]
![image](https://user-images.githubusercontent.com/31702109/46770893-0e382c80-cca6-11e8-8e7e-78be93354007.png)
and make it black or dark grey

**Comment by tylersweeney** [comment]
I can take this up

**Comment by AngelsProjects** [comment]
I can take it

**Comment by alinoancea** [comment]
I tried to resolve this issue with #29.

Regards.
