### ISSUE TITLE
Hacktoberfest 2018 Snippet Gradient

### ISSUE THREAD

**Issue by michaelcurry** [earlduque/Slack-Dark-Theme#2]
The gradient goes to white; making it very harsh on the eyes.  

I apologize in advance I did not make a pull request to fix this issue.  I wish I knew how to find the selector for this CSS rule...

I would rommend using a "darker" color instead of white.  Although I am not sure what color grey would be best.

![image](https://user-images.githubusercontent.com/2658933/38698969-9e2b22e6-3e4b-11e8-8f67-0bdf362cb0f0.png)

**Comment by calderaricaio** [comment]
Hi guys, do you want help with design for hacktoberfest contributions?

**Comment by calderaricaio** [comment]
Hi Guys! Fixed this issue with a PR waiting for approval!
https://github.com/earlduque/Slack-Dark-Theme/pull/9
