### ISSUE TITLE
Background is white on "All Thread" panel

### ISSUE THREAD

**Issue by tetz-akaneya** [earlduque/Slack-Dark-Theme#27]
I followed the guides and added the js snippet.
On most part it worked well but on `all threads` panel the background color for text area looks white as shown in the image below.
<img width="1048" alt="スクリーンショット 2019-03-23 22 07 25" src="https://user-images.githubusercontent.com/23702851/54866516-17323b80-4db8-11e9-8e5b-4ff12e5bac40.png">

Note: This is in Japanese mode. Perhaps that's the cause. Thanks!

**Comment by earlduque** [comment]
Committed https://github.com/earlduque/Slack-Dark-Theme/commit/0e2709a69de255165977ea04c2dc6e105f71a31b
