### ISSUE TITLE
Screen is still white.

### ISSUE THREAD

**Issue by TheDavidGage** [earlduque/Slack-Dark-Theme#4]
Hi there, my screen is still white after following the directions. Can you help me?
<img width="864" alt="screen shot 2018-07-29 at 15 50 38" src="https://user-images.githubusercontent.com/20408748/43370110-340e6fc0-9347-11e8-93ce-641616d3ea66.png">

**Comment by earlduque** [comment]
Slack updated there css a bit which broke the code, another contributor fixed it. Can you retry now?

**Comment by TheDavidGage** [comment]
IT WORKED! Thank you so much!
