### ISSUE TITLE
Issue with theme on Slack for Linux - v4.0.0

### ISSUE THREAD

**Issue by alinoancea** [earlduque/Slack-Dark-Theme#42]
Did anyone uses Slack for Linux and has problems with dark theme? I encountered this after updating Slack to v4.0.0.

For example:
Top header
![issue1](https://user-images.githubusercontent.com/18450669/61584205-77f63880-ab4c-11e9-9c45-e4741ea0450a.png)
or text box for writing messages
![issue2](https://user-images.githubusercontent.com/18450669/61584207-79bffc00-ab4c-11e9-995a-2d9d6572382a.png)

**Comment by BenFradet** [comment]
I'm on 4.0.0, and tried to edit ssb-interop.bundle.js in app.asar to no avail (no colors have changed)

**Comment by alpascale** [comment]
I'm experiencing the same on Slack for Windows v4.0.2.
![slack-dark-missing-style](https://user-images.githubusercontent.com/4072242/63865848-401ab600-c980-11e9-8ad4-68f35f6d0adb.png)
